language: r
sudo: false
cache: packages

r:
  - release
  - devel

r_github_packages:
    - jimhester/covr
    - berndbischl/BBmisc

after_success:
    - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
